services:
  postgres:
    image: postgres:16-alpine
    container_name: project-aletheia-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: aletheia
      POSTGRES_USER: aletheia
      POSTGRES_PASSWORD: aletheia
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
