services:
  db:
    image: postgres:16-alpine
    container_name: aletheia-db
    restart: unless-stopped
    env_file:
      - .env.docker
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
    command:
      - postgres
      - "-c"
      - "shared_buffers=256MB"
      - "-c"
      - "synchronous_commit=off"
      - "-c"
      - "max_wal_size=2GB"
      - "-c"
      - "checkpoint_completion_target=0.9"
      - "-c"
      - "effective_cache_size=768MB"
      - "-c"
      - "wal_compression=on"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

volumes:
  postgres_data:
