"""naming convention and index status

Revision ID: 2c7590dc5575
Revises: 03224a9134f0
Create Date: 2025-09-24 22:24:41.611292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c7590dc5575'
down_revision: Union[str, Sequence[str], None] = '03224a9134f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_LongTermMemory_id'), 'LongTermMemory', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_LongTermMemory_id'), table_name='LongTermMemory')
    # ### end Alembic commands ###
